# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - script: echo $(TestVariable)
      displayName: Job 1
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: Job2
    steps:
    - script: |
        echo Hi Job 2 - line 1
        echo Hi Job 2 - line 2
      displayName: Job 2
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: Job3
    steps:
    - script: echo Hello Job3
    displayName: Job 3
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: Job4
    steps:
    - script: echo Hello Job4
    displayName: Job 4
  

    
