replicas: 1
replicasMax: 1
cpuTargetPercentage: 50
ingress:
  name: foods-hub-common-service-sit
  # This will need to be set at deploy time as it differs from environment to environment
  domain: "foods.apps.mnscorpdev.net"
  subdomain: foods
  envdomain: "apps.mnscorpdev.net"
  cluster: fto
  tls_certificate: foods-apps-mnscorpdev-net

  # Mark ssl as true to enable SSL on this service
  ssl: true
  metric: false
  access_policy: 'public'
  proxybodysize: 'yes'
# Change below value if you want to deploy the application in a different namespace
namespace: foodshub-sit
resources:
  limits:
    memory: "1Gi"
    cpu: "1"
  requests:
    memory: "500Mi"
    cpu: "250m"
environment: sit
javaOption: "-Djava.net.preferIPv4Stack=true -Xms2048m -Xmx2048m"
newRelic:
  profile: "sit"
  config: "nonprod"
